sudo: false
language: python
python:
  - "3.5"
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  - conda create -q -n test-env --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py35-linux-conda.yml
  - source activate test-env
  - pip install -e .
  - pip install flake8
script:
  - python tax_credit/tests/test_eval_framework.py
  - python tax_credit/tests/test_framework_functions.py
  - python tax_credit/tests/test_plotting_functions.py
  - python tax_credit/tests/test_process_mocks.py
  - python tax_credit/tests/test_simulated_communities.py
  - python tax_credit/tests/test_taxa_manipulator.py
  - flake8 tax_credit

